spring:
  application.name: threads-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

grpc:
  server:
    port: 8073
    security:
      enabled: false
  client:
    wallService:
      address: "static://wallservice:8070"
      negotiationType: PLAINTEXT
